name: ğŸ« Release BitPuppy

on:
  release:
    types: [published]

jobs:
  checkout:
    name: ğŸ“ƒ Checkout
    runs-on: ubuntu-latest
    outputs:
      commit: ${{ steps.get_commit.outputs.commit }}
    steps:
      - name: Checkout Code
        id: get_commit
        uses: actions/checkout@v4

      - name: Save Commit SHA
        run: echo "commit=${{ github.sha }}" >> $GITHUB_OUTPUT

  build:
    name: ğŸ—ï¸ Build (C++)
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y libyaml-dev libjson-c-dev

      - name: Build with CMake
        run: |
          rm -rf build bin
          mkdir -p build bin
          cd build
          cmake ..
          make
          cp bitpup ../bin/bitpup

      - name: Upload Binaries as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bitey-binaries
          path: bin/

  release:
    name: ğŸ“¤ Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Compiled Binaries
        uses: actions/download-artifact@v4
        with:
          name: bitey-binaries
          path: bin/

      - name: Attach to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
